version: '3'

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
    restart: always
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
